# Generated by Django 2.2.6 on 2020-06-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='msg_for_rcvr',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='receiver_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='sender_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
