# Generated by Django 2.2.6 on 2019-10-09 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0002_auto_20191009_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('file', models.FileField(max_length=400, null=True, upload_to='file_content/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=2000)),
            ],
        ),
    ]
