# Generated by Django 2.2.6 on 2019-10-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0003_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='text',
            field=models.TextField(max_length=3000),
        ),
    ]
