# Generated by Django 2.2.6 on 2019-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0004_auto_20191009_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
