# Generated by Django 2.2.6 on 2019-10-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0005_auto_20191009_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_type',
            field=models.CharField(choices=[('im', 'Image'), ('vid', 'Video')], default='im', max_length=50),
        ),
    ]
