# Generated by Django 2.2.6 on 2019-10-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0006_filemodel_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='file',
            new_name='file_here',
        ),
    ]
