# Generated by Django 2.2.6 on 2019-10-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0007_auto_20191013_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='country',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
