# Generated by Django 2.2.6 on 2019-10-14 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0008_auto_20191013_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_for_rcvr', models.TextField(blank=True, max_length=3000, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_email', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
