# Generated by Django 2.2.6 on 2019-10-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0009_couponmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
