# Generated by Django 2.2.6 on 2019-10-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0011_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_here1',
            field=models.FileField(max_length=400, null=True, upload_to='file_content/'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='text1',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
