# Generated by Django 2.2.6 on 2019-10-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0012_auto_20191029_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='msg1_for_rcvr',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='receiver1_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
