# Generated by Django 2.2.6 on 2019-10-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0013_auto_20191029_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_here1',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to='file_content/'),
        ),
    ]
