# Generated by Django 2.2.6 on 2019-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0014_auto_20191029_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='amount',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
