# Generated by Django 2.2.6 on 2019-11-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0015_couponmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponmodel',
            name='msg1_for_rcvr',
        ),
        migrations.RemoveField(
            model_name='couponmodel',
            name='receiver1_email',
        ),
    ]
