# Generated by Django 2.2.6 on 2019-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0016_auto_20191109_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_here2',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to='file_content/'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_here3',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to='file_content/'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_here4',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to='file_content/'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_type1',
            field=models.CharField(choices=[('im', 'Image'), ('vid', 'Video')], default='im', max_length=50),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_type2',
            field=models.CharField(choices=[('im', 'Image'), ('vid', 'Video')], default='im', max_length=50),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_type3',
            field=models.CharField(choices=[('im', 'Image'), ('vid', 'Video')], default='im', max_length=50),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_type4',
            field=models.CharField(choices=[('im', 'Image'), ('vid', 'Video')], default='im', max_length=50),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='text2',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='text3',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='text4',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
