# Generated by Django 2.2.6 on 2020-04-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0017_auto_20191119_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='info',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='url',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=2000, null=True)),
                ('country', models.CharField(blank=True, max_length=2000, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_extra', to='fileman.FileModel')),
            ],
        ),
    ]
