# Generated by Django 2.2.6 on 2020-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0022_paymentprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='sender_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
