# Generated by Django 2.2.6 on 2020-05-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0023_auto_20200517_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponmodel',
            name='msg_for_rcvr',
        ),
        migrations.RemoveField(
            model_name='couponmodel',
            name='receiver_email',
        ),
        migrations.RemoveField(
            model_name='couponmodel',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='couponmodel',
            name='sender_name',
        ),
    ]
