# Generated by Django 2.2.6 on 2020-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0024_auto_20200518_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds_required', models.IntegerField(default=0)),
                ('limited_pebbles', models.IntegerField(default=0)),
            ],
        ),
    ]
