# Generated by Django 2.2.6 on 2020-05-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0025_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='remaining_pebbles',
            field=models.IntegerField(default=0),
        ),
    ]
