# Generated by Django 2.2.6 on 2020-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0026_funds_remaining_pebbles'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprogress',
            name='pebble_meter',
            field=models.BooleanField(default=False),
        ),
    ]
